### ISSUE TITLE
Set initial projection state on backing store at first mount

### ISSUE THREAD

**Issue by chrisd8088** [github/libprojfs#71]
To utilize libprojfs with VFSForGit, we need client-managed mechanism by which to set the initial projection state on the top-level mount point directory.  Currently, we do this in libprojfs by testing, at mount time, [whether the mount point directory is empty](https://github.com/github/libprojfs/blob/9f36ea1b4a3a38d97fd865049fcf11fd9ffe7435/lib/projfs.c#L1475).

However, when used with VFSForGit, we want to set the flag once sometime after the user runs `gvfs clone`, at which point the directory will already have `.git` and `.gitattributes` in it, so our default `check_dir_empty()` test will not work.

A simple fix is to have the VFSForGit C# code "manually" set the `user.projection.empty` flag to `y` on the directory after `gvfs clone` runs.  But this breaks our API abstraction, which assumes this flag is managed by libprojfs.

From the libprojfs perspective, an option which aligns well with libfuse is to accept an [`args` array](https://github.com/libfuse/libfuse/blob/7a5e1a9a9a61416c759ce02a48e600814fd13711/include/fuse_opt.h#L109) of [option arguments](https://github.com/libfuse/libfuse/blob/7a5e1a9a9a61416c759ce02a48e600814fd13711/lib/fuse.c#L4599), which are [parsed](https://github.com/libfuse/libfuse/blob/7a5e1a9a9a61416c759ce02a48e600814fd13711/lib/fuse.c#L4851) at the time the FUSE filesystem handle is created.  Similarly, our [`projfs_new()`](https://github.com/github/libprojfs/blob/9f36ea1b4a3a38d97fd865049fcf11fd9ffe7435/lib/projfs.c#L1268) function could accept a list of arguments to parse, including (potentially) supported FUSE arguments like `-o debug` which could be passed down to `fuse_new()` instead of our current [fixed compile-time argument array](https://github.com/github/libprojfs/blob/9f36ea1b4a3a38d97fd865049fcf11fd9ffe7435/lib/projfs.c#L1442) to FUSE.

If we implement such an option (e.g., `-o init` or `--initial-mount` or [something like that](https://github.com/libfuse/libfuse/blob/7a5e1a9a9a61416c759ce02a48e600814fd13711/lib/mount.c#L140)) following, for instance, the [example](https://github.com/libfuse/libfuse/blob/7a5e1a9a9a61416c759ce02a48e600814fd13711/lib/mount.c#L140) of the libfuse `mount` utility, then we will want to pass an additional `bool` "initial mount" flag argument to [`StartVirtualizationInstance()`](https://github.com/github/VFSForGit/blob/c94ce90cb43d8886fdb1344dc14c5768cf8d0645/ProjFS.Linux/PrjFSLib.Linux.Managed/VirtualizationInstance.cs#L34) which can be converted into the appropriate argument array and passed down to `projfs_new()`.

To determine the value of this flag will be an interesting effort, since we do not want to set it on every `gvfs mount` operation, only the first one.  Two options present themselves:
1. Perform a call to `StartVirtualizationInstance()` at the end of `gvfs clone`, perhaps in the [`TryPrepareFolderForCallbacks()`](https://github.com/github/VFSForGit/blob/54dc07117a1a09a40907a7f738a06b4b9aebaed5/GVFS/GVFS.Platform.Linux/ProjFSLib.cs#L50) method which is run at the very end of the [`CloneVerb`](https://github.com/microsoft/VFSForGit/blob/d93e2685d5106a4d9d826576b3177cb33adb78aa/GVFS/GVFS/CommandLine/CloneVerb.cs#L649) process.
2. At the start of the `gvfs mount` process, check whether the `.gvfs/lower` directory contains only `.git` and `.gitattributes`, and if so, set the "initial mount" flag to the [`StartVirtualizationInstance()`](https://github.com/github/VFSForGit/blob/54dc07117a1a09a40907a7f738a06b4b9aebaed5/GVFS/GVFS.Platform.Linux/LinuxFileSystemVirtualizer.cs#L227) call.

I am personally inclined toward the second option, as it effectively lifts the "is this directory empty" logic up to the client program's level, where it can determine if the directory is empty according to its own rules (in this case, if it only has the expected post-clone contents), and because it should avoid the need for a full mount/unmount cycle at the end of the cloning step, which feels like a more fragile solution overall.

See also github/VFSForGit#20.

**Comment by kivikakk** [comment]
> I am personally inclined toward the second option, as it effectively lifts the "is this directory empty" logic up to the client program's level, where it can determine if the directory is empty according to its own rules (in this case, if it only has the expected post-clone contents), and because it should avoid the need for a full mount/unmount cycle at the end of the cloning step, which feels like a more fragile solution overall.

This sounds most correct to me 👍
